package com.dbpsecurity.dbpcheckin.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class Attendance(
    val id: String? = null, // ID might be generated by DB
    @SerialName("created_at") val createdAt: String? = null,
    @SerialName("user_id") val userId: String,
    val status: String,
    @SerialName("image_url") val imageUrl: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null
)

